name: Publish

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'

jobs:
  build:
    name: Build Jar
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Upload jar to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/<WHATEVER THE JAR NAME IS WHEN YOU BUILD IT LOCALLY>
        asset_name: <WHATEEVER THE JAR SHOULD BE CALLED ON RELEASE, MAKE SURE TO ADD .jar AT THE END>
        tag: ${{ github.ref }}
        overwrite: true
        body: "Mhm release notes"
